[package]
name = "zommi-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
futures-util.workspace = true
rand_core.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
url.workspace = true
uuid.workspace = true
wait-timeout.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
