<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>focalet-browser-capture</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Focalet.Capture.Core/Focalet.Capture.Core.csproj" />
  </ItemGroup>
</Project>
