<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>zommi-browser-capture</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Zommi.Capture.Core/Zommi.Capture.Core.csproj" />
  </ItemGroup>
</Project>
